language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

before_script:
  - composer install --prefer-source

script:
  - mkdir -p builds/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --bootstrap tests/bootstrap.php --configuration tests/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls
